amcl:
  ros__parameters:
    use_sim_time: true
    global_frame_id: "map"
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"
    scan_topic: "/scan"
    robot_model_type: "nav2_amcl::OmniMotionModel"
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    max_particles: 2000
    min_particles: 500
    update_min_a: 0.2
    update_min_d: 0.25
    laser_max_range: 25.0 
    laser_min_range: 0.05
    laser_model_type: "likelihood_field"
    max_beams: 60
    z_hit: 0.5
    z_rand: 0.5
    z_max: 0.05
    z_short: 0.05
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0

map_server:
  ros__parameters:
    use_sim_time: true

planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 10.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.5
      use_astar: false    
      allow_unknown: false

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: map
      robot_base_frame: base_footprint
      footprint: '[ [0.36, 0.25], [0.36, -0.25], [-0.36, -0.25], [-0.36, 0.25] ]'
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer", "keepout_filter"]

      keepout_filter:
        plugin: "nav2_costmap_2d::KeepoutFilter"
        enabled: True
        filter_info_topic: "/costmap_filter_info"

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
        
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        # Đã xóa các cam cũ, chỉ giữ Lidar trước, Lidar sau và Camera mới
        observation_sources: scan scan_rear camera_pointcloud
        
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          min_obstacle_height: 0.05   
          obstacle_range: 8.0         
          raytrace_range: 10.0
          clearing: true
          marking: true
          data_type: "LaserScan"

        scan_rear:
          topic: /scan_rear
          max_obstacle_height: 2.0
          min_obstacle_height: 0.05   
          obstacle_range: 8.0         
          raytrace_range: 10.0
          clearing: true
          marking: true
          data_type: "LaserScan"
       
        camera_pointcloud:
          topic: "/camera/points"
          sensor_frame: "camera_link"
          max_obstacle_height: 3.0
          min_obstacle_height: 0.15    
          clearing: false              # GIỮ LẠI TRÍ NHỚ VẬT CẢN
          marking: true
          data_type: "PointCloud2"
          raytrace_max_range: 10.0
          raytrace_min_range: 0.1
          obstacle_max_range: 8.0
          obstacle_min_range: 0.1
          
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 1.0
      always_send_full_costmap: true

controller_server:
  ros__parameters:
    use_sim_time: true
    enable_stamped_cmd_vel: true 
    controller_frequency: 20.0
    controller_plugins: ["FollowPath"]
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["general_goal_checker"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    general_goal_checker:
      stateful: true
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.5
      yaw_goal_tolerance: 0.5

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: false
      
      min_vel_x: -0.5
      max_vel_x: 1.5 
      min_vel_y: 0.0
      max_vel_y: 0.0
      max_vel_theta: 2.0
      
      min_speed_xy: 0.04
      max_speed_xy: 1.0
      min_speed_theta: 0.3
      
      acc_lim_x: 1.0
      acc_lim_y: 0.0
      acc_lim_theta: 2.0
      decel_lim_x: -2.0
      decel_lim_y: 0.0
      decel_lim_theta: -3.2

      sim_time: 1.7
      vx_samples: 30
      vy_samples: 1
      vtheta_samples: 60
      
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist", "PreferForward"] 
      
      BaseObstacle.scale: 0.06 
      PathAlign.scale: 80.0 
      GoalAlign.scale: 10.0 
      PathDist.scale: 80.0 
      GoalDist.scale: 10.0 
      RotateToGoal.scale: 10.0 
      Oscillation.scale: 20.0 
      PreferForward.scale: 5.0

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: odom
      robot_base_frame: base_footprint
      rolling_window: true
      width: 8
      height: 8
      resolution: 0.05
      footprint: '[ [0.36, 0.25], [0.36, -0.25], [-0.36, -0.25], [-0.36, 0.25] ]'

      plugins: ["voxel_layer", "keepout_filter", "inflation_layer"]

      keepout_filter:
        plugin: "nav2_costmap_2d::KeepoutFilter"
        enabled: True
        filter_info_topic: "/costmap_filter_info"
      
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: true
        publish_voxel_map: true
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 40
        max_obstacle_height: 2.0
        mark_threshold: 0
        # Đã xóa các cam cũ, chỉ giữ Lidar và Camera mới
        observation_sources: scan camera_pointcloud
        
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          min_obstacle_height: 0.05   
          obstacle_range: 8.0         
          raytrace_range: 10.0
          clearing: true
          marking: true
          data_type: "LaserScan"
          
        camera_pointcloud:
          topic: "/camera/points"      
          sensor_frame: "camera_link"
          max_obstacle_height: 3.0
          min_obstacle_height: 0.15
          clearing: False              # BẮT BUỘC FALSE ĐỂ CHỐNG TÀNG HÌNH
          marking: true
          data_type: "PointCloud2"     
          raytrace_max_range: 5.0
          raytrace_min_range: 0.1
          obstacle_max_range: 4.5
          obstacle_min_range: 0.1

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 2.5
        inflation_radius: 0.8

bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: base_footprint
   
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"

behavior_server:
  ros__parameters:
    use_sim_time: true
    enable_stamped_cmd_vel: true
    local_costmap_topic: local_costmap/costmap_raw
    global_costmap_topic: global_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"
    local_frame: odom
    global_frame: map
    robot_base_frame: base_footprint
    transform_tolerance: 0.1

waypoint_follower:
  ros__parameters:
    use_sim_time: true
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"   
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      waypoint_pause_duration: 1000

costmap_filter_info_server:
  ros__parameters:
    use_sim_time: true
    type: 0
    filter_info_topic: "/costmap_filter_info"
    mask_topic: "/keepout_filter_mask"
    base: 0.0
    multiplier: 1.0

filter_mask_server:
  ros__parameters:
    use_sim_time: true
    frame_id: "map"
    topic_name: "/keepout_filter_mask"
    yaml_filename: "/home/pham-van-de/ros2_ws/src/robot_omni/maps/keepout_mask.yaml"